### PR TITLE
Kerberoast roast command is now OPSEC safe

### PR DESCRIPTION
**Pull request by Firat-NVISO**
Changed Kerberoast so it doesn't perform the heavily signatured LDAP query when you use the roast command, as it was unnecessary for targeted kerberoasting. Also added dynamic architecture selection in the cna script + building of x86 and x64 in makefile (didn't do this for everything).

### CODE REVIEW

**Comment by Cn33liz** [comment]
> Changed Kerberoast so it doesn't perform the heavily signatured LDAP query when you use the roast command, as it was unnecessary for targeted kerberoasting. Also added dynamic architecture selection in the cna script + building of x86 and x64 in makefile (didn't do this for everything).

Nice, i'll take a look at the changes asap.

**Comment by Firat-NVISO** [comment]
Thanks! It's not a big pull request, but I learned the hard way that Kerberoast performs that ldap query when you specify one user (was late and I was tired, didn't test in our lab first 😅). Just did some quick patching and using it again now.

Kind regards,

Firat

________________________________

**Comment by Cn33liz** [comment]
Hi, i used your feedback/changes en made an update to the Kerberoast code. Code is bit different then your change but works the same. Could you check if this works for you?

**Comment by Firat-NVISO** [comment]
Hey, it looks good, but is the UserAccountControl check really necessary for a targeted Kerberoast?
If you’re doing a targeted kerberoast, you should know the details about the account (e.g. enabled or not). The current query might still look suspicious according to some rules.

Kind regards!


***@***.***
Firat Acar
NVISO. Security. Research. Risk.
M: +49 175 6995665 ▪ E: ***@***.******@***.***>
www.nviso.eu<http://www.nviso.eu/>
***@***.******@***.******@***.******@***.***<https://blog.nviso.eu/>

NVISO GmbH, Holzgraben 5, 60313 Frankfurt am Main
Amtsgericht Frankfurt, HRB 113154 – USt. ID DE320424488

**Comment by Firat-NVISO** [comment]
Hey, 

It looks good, but is the UserAccountControl check really necessary for a targeted Kerberoast? 
If you’re doing a targeted kerberoast, you should know the details about the account (e.g. enabled or not). The current query might still look suspicious according to some rules.

Kind regards!

**Comment by Cn33liz** [comment]
Good one.. If it still looks suspicious then i think it's best to remove it from the query.
I'll update asap.

**Comment by Firat-NVISO** [comment]
Thank you! 
I wouldn't say suspicious per se, but it's unnecessary and at least part of quite some signatured queries.

**Pull request closed without merging**
